server:  
  port: ${PORT:4444}

spring:  
  application:
    name: product-service
  data:
    mongodb:
      host: ds237717.mlab.com
      port: 37717
      database: account-service
      username: account 
      password: reis2000
      
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true